### ISSUE TITLE
Add "Send feedback" option

### ISSUE THREAD

**Issue by dieechtenilente** [dieechtenilente/alcoholtestapp#14]
- HTML-Request with Version, Name, Text
- PHP-Mailer on my server sending a e-mail to my address

**Comment by dieechtenilente** [comment]
@okitec Maybe you want to do this :D

**Comment by okitec** [comment]
I don't do PHP.

*However*, I could write a Go HTTP server that interprets the JSON, then sends you mail, but you'll need to give the program a sender mail account it can use (incl. a password), and you'll need to give me info about the exact request you want to send. This won't be a lot of work.

You could then run that server on your rpi on some free port, e.g. `12345` (don't forget port-forwarding).

**Comment by okitec** [comment]
See my commit 6701d6e8d500b00ea29bc3d26055e95ddbc5555c.

I'm missing the format you want to send to the server; I'll make a pull request once it's totally finished.

You will need [Go](https://golang.org/dl/), preferably on your target machine (rpi, I guess) to avoid the need for cross-compilation (even though that's really easy too).

**Comment by dieechtenilente** [comment]
That .. was quick. Im currently working on it ^^

**Comment by dieechtenilente** [comment]
You can see the format I'm using here: 4a723621f5e7fd56f1510187e9fb10db51e3cef2

**Comment by okitec** [comment]
I wouldn't have chosen Go for this had I not known it would be painless.

I guess your app will make a POST or GET request with some JSON body. I need precisely that info to continue. Something along the lines of 

```json
{
    "version": "a.b.c",
    "reply-address": "derp@foo.biz",
    "subject": "this app estí nice",
    "body": "Blah blah blah"
}
```

The reply address would be an optional e-mail address so you can communicate if needed.

**Update: just saw your latest commit**

Could you give me an example JSON? Also, don't forget to tell the user what you'll send, and ask for confirmation to avoid privacy/data security problems.

**Comment by okitec** [comment]
I'll finish the server side now.

**Comment by dieechtenilente** [comment]
Okay. I will generate a example-JSON and add privacy-stuff.

**Comment by dieechtenilente** [comment]
> I think adding an reply address and a subject to your current data would be swell.

A good point. I first thought about raw feedback without any reply (it is common practice) and after releasing it in the PlayStore, I reply to reports there.

**Comment by okitec** [comment]
I don't need the example JSON, I'm already done now ;)

**Comment by dieechtenilente** [comment]
Okay xD
However, I will do one for the `README.md`  ^u^

**Comment by okitec** [comment]
Yeah, documentation is paramount.

Also, would you mind removing the underscores in `os_ver` and `os_api_lvl` pls (see my comment about that)?

Third, I think the JSON is missing the version number of your app (an important thing, I'd say).

**Comment by dieechtenilente** [comment]
Oh snap. Somehow, I removed the version number. It was present.
The underscores will be removed in the next commit.

**Comment by dieechtenilente** [comment]
Here you go, sir: aa07edae4fad5cadaabfdff611f7f2a6c5c44cc5

**Comment by okitec** [comment]
Could you temporarily disable HTTPS and try to connect to `oquasinus.duckdns,org:9444` with your app?

**Comment by dieechtenilente** [comment]
Yup. Wait a few minutes

**Comment by dieechtenilente** [comment]
Feedback sent.
