### ISSUE TITLE
After deleting one of two users, the "switch user" option is still shown

### ISSUE THREAD

**Issue by dieechtenilente** [dieechtenilente/alcoholtestapp#15]

**Comment by okitec** [comment]
Just rename it "select user" and show a list of users (as I guess you do). If there's only one, the list will have one entry, which you can *select*. No *switching*. Problem circumvented :P

**Comment by dieechtenilente** [comment]
But then you still have the useless "show the only user existing" button which shows the user and a button to add a new one as well as a "add user" button in the menu. I don' like it :/

**Comment by okitec** [comment]
Yeah, my idea was really tongue-in-cheek.

**Comment by dieechtenilente** [comment]
But it will close an issue.. :D (and probably create a new one about how useless the other button is)

**Comment by dieechtenilente** [comment]
There you go :D
