### ISSUE TITLE
Put bac calculation into a service

### ISSUE THREAD

**Issue by dieechtenilente** [dieechtenilente/alcoholtestapp#18]
Creating a background service that calculates the bac current bac. It should constantly (every 5 min or so) update the notification and end itself if bac is 0 to free ram.

**Comment by leletec** [comment]
AlarmManager could be useful for this: https://stackoverflow.com/questions/4452565/start-app-at-a-specific-time

**Comment by dieechtenilente** [comment]
But then I have to generate a lot of events, because the bac calculation is more or less in realtime.

**Comment by dieechtenilente** [comment]
Or update it every 5 minutes/when a `Drink` "expires"
