### ISSUE TITLE
[MASTER] Reworking everything*

### ISSUE THREAD

**Issue by dieechtenilente** [dieechtenilente/alcoholtestapp#43]
*not quite everything

The app per se is quite nice - but it's working like a piece of poop. Reworking is necessary! (this time in a more organized and correct way)

`User`
- name: String
- age: int
- isMale: boolean
- weight: int
- height: int
- created: long
- drinks[]: Drink <-- now a ArrayList

`Drink`
- name: String
- description: String
- concumePoint: long
- degrationPoint: long <-- calculated by the app (**)
- content[]: Content

Content
- name: String
- alcContent: double (as "%")
- amount: double ( as "ml")

Mixture
- name:String
- content[]: Content
- description: String

-> A `Mixture` with `Content`s can be consumed by a `User` resulting in a `Drink`.

Custom Mixtures will be back soon.

Moving everything in one package resulting in the possibility to make `protected` variables. And it doesn't look that terrible.

** Redoing the calculation of consumed drinks

In the past, the depletion of drinks was quite mysterious. I do personally don't know why I thought that way but now the depletion is calculated like this:

drink 1 depletion point =  `consumption time of drink 1` + `depletion time of drink 1`
drink 2 depletion point =  `consumption time of drink 1` + `depletion time of drink 1` + `depletion time of drink 2`
drink 3 depletion point =  `consumption time of drink 1` + `depletion time of drink 1` + `depletion time of drink 2` + `depletion time of drink 3` 
and so on

In this way, the first drink will deplete completely until the next is going to deplete. If you remove drink 2 the calculation is still correct because it is calculated after every refresh of the drink-list.

**Comment by okitec** [comment]
Ohh, work is being done again, cool!

One thing, though:

> Moving everything in one package resulting in the possibility to make protected variables. And it doesn't look that terrible.

I really like that you put it into one package. But if you're happy about being able to use protected variables, you might as well make them public. Java's visibility system is broken, ah well.

**Comment by okitec** [comment]
I agree. Choose the simple way.
