### ISSUE TITLE
Deleting the wrong drink

### ISSUE THREAD

**Issue by dieechtenilente** [dieechtenilente/alcoholtestapp#8]
If you have two or more users and (e.g.) two of them have drinks, deleting a drink from a user, created after the first user, will delete the drinks from the first user.

**Comment by okitec** [comment]
You should have a list of `Drink`s in the `User` class since that's all users are: a list of drinks with some additional data (very much like real life). `Drink` need not be stored elsewhere.

**Comment by dieechtenilente** [comment]
Great idea. Easier than having another list mapping user and drinks.

**Comment by okitec** [comment]
I had been wondering why you'd have this Drink design but I didn't know enough to question it.

Data structures are the important part; code is the filler.
